name: workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run eslint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: npm ci;
      - name: Jest Tests
        run: npm run test:jest
  ssh:
    if: github.ref == 'refs/heads/main'
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH}}
          port: ${{secrets.PORT}}
          script: |
            cd ${{secrets.FOLDER}}
            rm -rf react-tasker
            git clone git@github.com:devkirkir/react-tasker.git
            docker build ./react-tasker -t tasker
